
export let BRAND_FOOD_REQUEST = "BRAND_FOOD_REQUEST";
export let BRAND_FOOD_SUCCESS = "BRAND_FOOD_SUCCESS";
export let BRAND_FOOD_FAILURE = "BRAND_FOOD_FAILURE";
export let BRAND_FOOD_RESET = "BRAND_FOOD_RESET";

export let FOOD_REQUEST = "FOOD_REQUEST";
export let FOOD_SUCCESS = "FOOD_SUCCESS";
export let FOOD_FAILURE = "FOOD_FAILURE";

export let FOOD_ITEM_REQUEST = "FOOD_ITEM_REQUEST";
export let FOOD_ITEM_SUCCESS = "FOOD_ITEM_SUCCESS";
export let FOOD_ITEM_FAILURE = "FOOD_ITEM_FAILURE";

export let RESTAURANT_REQUEST = "RESTAURANT_REQUEST";
export let RESTAURANT_SUCCESS = "RESTAURANT_SUCCESS";
export let RESTAURANT_FAILURE = "RESTAURANT_FAILURE";

